# Generated by Django 4.2.10 on 2024-08-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("course", "student"), name="unique_course_student"
            ),
        ),
    ]
