# Generated by Django 4.2.10 on 2024-08-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveBigIntegerField(verbose_name="Стоимость курса"),
        ),
    ]
